[_dq] # required
application = 'DevQon' # must be unique for each application
root_directory = ['$HOME','.dq'] # name of folder for _all_ applicable DownQuark projects

[devqon] # must be lowercase of application name as a single word with all `/[^a-z]/` removed
auto_update = true
debug = false

[devqon.directory]
application = ['$RESOURCE','../../..']
home = ['dq.DIRECTORY','devqon']
resource = ['$RESOURCE']

[devqon.logging]
level = 'WARN'
output = ['std.out']

# TODO - replace `todo.` with `devqon` namespace when integrated
[[todo.database]]
id = 'ARANGO_DB'
url = "TODO: arangodb url"

[[todo.database]]
id = 'MARIA_DB'
url = "TODO: mariadb url"